name: portfolio_miguel_belotto
description: A new Flutter project.

publish_to: "none"

version: 2.2.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/panda.jpg
    - assets/img/bot_fit.png
    - assets/img/tiktokemon.png
    - assets/img/twitterclone.png
